### ISSUE TITLE
The maximum of redis_port and http_port supported value is 32767 

### ISSUE THREAD

**Issue by hihiyf** [nicolasff/webdis#142] opened 2017-07-24 11:40 UTC
phenomenon：
modify redis_port from 6379 to 33505
  "redis_port":6379 =》"redis_port":33505
webdis.log report  "[9530] 24 Jul 15:03:17 46 Connection failed: Servname not supported for ai_socktype"

reason:
The type of redis_port and http_port is  'short' .    The range of the short type is -32767-32767. Need to modify the type of unsigned short or int. 

thanks :)

**Comment by nicolasff** [comment] 2017-07-24 21:01
This is a duplicate of #113.

**Closed by nicolasff** 2017-07-24 21:01 UTC
